# Generated by Django 4.1.3 on 2022-11-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productinventory",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user id to identify the user who added the inventory item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="productinventory",
            name="product",
            field=models.ForeignKey(
                help_text="The product id to identify the product associated with the inventory item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_inventory",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productinventory",
            name="supplier",
            field=models.ForeignKey(
                help_text="The supplier id to identify the supplier associated with the inventory item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_inventory",
                to="products.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="productinventory",
            name="updated_By",
            field=models.ForeignKey(
                help_text="The user id to identify the user who updated the inventory item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeManyToManyField(
                related_query_name="category", to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_type",
                to="products.producttype",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="product_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_product_inventory",
                to="products.productinventory",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="format: not required",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="products.category",
                verbose_name="parent of category",
            ),
        ),
    ]
